config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do
  resources :projects do
    resources :codes
  end
end

app/models/code.rb
class Code < ActiveRecord::Base	
  unloadable

  belongs_to :project
  
  validates_presence_of :name, :gitlab_link
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  unloadable

  before_filter :find_project, :authorize

  def index
    @codes = @project.codes
  end  

  def new
    @code = Code.new
  end

  def create    
    @code = Code.new(params[:code])
    @code.project = @project
    if @code.save
      respond_to do |format|
        format.html do
          flash[:notice] = l(:notice_successful_create)
          redirect_to :controller => 'projects', :action => 'settings', :tab => 'code', :id => @project
        end
      end
    else
      respond_to do |format|
        format.html { render :action => 'new' }
      end 
    end
  end

  def edit
    @code = Code.find(params[:id])
  end  

  def update
    @code = Code.find(params[:id])
    @code.project = @project
    @code.attributes = params[:code]
    if @code.save
      respond_to do |format|
        format.html do
          flash[:notice] = l(:notice_successful_update)
          redirect_to :controller => 'projects', :action => 'settings', :tab => 'code', :id => @project
        end
      end
    else
      respond_to do |format|
        format.html { render :action => 'edit' }
      end 
    end     
  end

  def destroy
    @code = Code.find(params[:id])
    @code.destroy
    respond_to do |format|
      flash[:notice] = l(:notice_successful_delete)
      format.html { redirect_to :controller => 'projects', :action => 'settings', :id => @project, :tab => 'code' }
    end    
  end

  private

    def find_project
      @project = Project.find(params[:project_id])
    end  
end

app/views/codes/_form.html.erb
<%= error_messages_for 'code' %>

<div class="box tabular">
	<p>
		<%= f.text_field :name, :size => 30, :required => true %>
	</p>
	<p>
		<%= f.text_field :gitlab_link, :size => 30, :required => true %>
	</p>
	<p>
		<%= f.text_field :description, :size => 30 %></p>
</div>

app/views/codes/_index.html.erb
<% if @project.codes %>
  <table class="list">
    <thead><tr>
      <th><%= t(:field_name) %></th>
      <th><%= t(:field_gitlab_link) %></th>
      <th><%= t(:field_description) %></th>
      <th></th>
    </tr></thead>
    <tbody>
      <% for code in  @project.codes %>
        <% unless code.new_record? %>
          <tr class="<%= cycle 'odd', 'even' %>">
            <td><%= code.name %></td>
            <td><%= code.gitlab_link %></td>
            <td><%= code.description %></td>
            <td class="buttons">
            	<% if User.current.allowed_to?(:manage_code, @project) %>          
                <%= link_to l(:button_edit), edit_project_code_path(@project, code), :class => 'icon icon-edit' %>
                <%= delete_link project_code_path(@project, code) %>
        		  <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>  
<p>
  <%= link_to t(:new_code), new_project_code_path(@project), :class => 'icon icon-add'  if User.current. 
       allowed_to?(:manage_code, @project) %>
</p>

app/views/codes/edit.html.erb
<h2><%= t(:edit_code) %></h2>
<%= labelled_form_for @code, :url => project_code_path(@project, @code), :html => {:method => :put} do |f| %>
	<%= render :partial => 'codes/form', :locals => { :f => f } %>
	<%= submit_tag l(:button_save) %>
<% end %>

app/views/codes/new.html.erb
<h2><%= t(:new_code) %></h2>
<%= labelled_form_for @code, :url => project_codes_path(@project) do |f| %>
	<%= render :partial => 'codes/form', :locals => { :f => f } %>
	<%= submit_tag l(:button_save) %>
<% end %>